services:
  orders-api:
    command: /start
    container_name: orders_api
    build:
      context: .
    env_file:
      - ./.environment/.env.django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - ./.environment/.env.postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - backend
    ports:
      - "6379:6379"

networks:
  backend:
    driver: bridge

volumes:
  static_volume:
  postgres_data:
