# Generated by Django 5.2.7 on 2025-10-23 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('processed', models.BooleanField(default=False)),
                ('body', models.JSONField()),
            ],
        ),
    ]
