services:
  orders-api:
    container_name: orders_api
    build:
      context: .
    command: /start
    env_file:
      - ./.environment/.env.django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - ./.environment/.env.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  relay-service:
    container_name: relay_service
    build:
      context: ../Relay-Service/
    env_file:
      - ./.environment/.env.relay
    volumes:
      - ../Relay-Service:/app
    depends_on:
      - postgres
      - rabbitmq
    restart: always

networks:
  default:
    driver: bridge

volumes:
  static_volume:
  postgres_data:
